name: workflow_demo

on:
  push:
    branches: [main]

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  job1:
    runs-on: aliyun
    steps:
      - run: sleep 4
      - run: echo "Success!"