name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  fruits:
    env:
      B1: b
    runs-on: ubuntu-latest
    steps:
      - name: print_fruits
        env:
          A1: a ${{env.B1}}
        run: echo "${{env.A1}}"
      - name: print_github
        run: echo "${toJSON(github)}"