name: download-artifact

on: pull_request

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  job:
    runs-on: ubuntu-latest
    needs: job0
    if: ${{ always() }}
    steps:
      - run: echo "Success!"