name: workflow_demo

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lha
      - run: pwd
      - run: ls -lha ~
      - run: npm config list -l
      - run: npm cache
# 使用 cache 缓存依赖