name: workflow_demo

on:
  push:
    branches: [main]

env:
  SHA_1: ${{ github['sha'] }}
  SHA_2: ${{ github.sha }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo $SHA_1 | $SHA_2