name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  fruits:
    runs-on: ubuntu-latest
    env:
      FRUITS: '[{"name": "apple", "quantity": 1}, {"name": "orange", "quantity": 2}, {"name": "pear", "quantity": 1}]'
    steps:
      - name: print_fruits
        env:
          FRUIT_NAMES: ${{ fromJSON(env.FRUITS).*.name }}
        run: echo $FRUIT_NAMES