name: workflow_demo

on:
  push:
    branches: [main]

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
      - run: echo "Success3!"