name: workflow_demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    steps:
      - run: echo "job!"
  job-failure:
    runs-on: aliyun
    needs: job
    if: ${{ failure() }}
    steps:
      - run: echo "failure!"
  job-success:
    runs-on: aliyun
    needs: job
    if: ${{ success() }}
    steps:
      - run: echo "success!"
  job-always:
    runs-on: aliyun
    needs: job
    if: ${{ always() }}
    steps:
      - run: echo "always!"
  job-cancelled:
    runs-on: aliyun
    needs: job
    if: ${{ cancelled() }}
    steps:
      - run: echo "cancelled!"
