name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  print_fruit_name:
    runs-on: ubuntu-latest
    env:
      fruits: '[{"name": "apple", "quantity": 1}, {"name": "orange", "quantity": 2}, {"name": "pear", "quantity": 1}]'
    steps:
      - run: echo $fruits
