name: workflow_demo2

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true
        default: ""

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.name }}!"
