name: workflow_demo

on: pull_request

jobs:
  job1:
    runs-on: aliyun
    env:
      GREETING: Hello
    steps:
      - run: echo ${{ env.GREETING }}
  job2:
    runs-on: aliyun
    steps:
      - name: Step Env
        env:
          OS: ${{runner.os}}
        run: echo "$GREETING ${{ env.OS }}"
