name: workflow_demo

on: pull_request

jobs:

  job2:
    runs-on: aliyun
    env:
      GREETING: Hello
    steps:
      - name: Step Env
        env:
          OS: ${{runner.os}}
        run: echo $GREETING
