name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  fruits:
    runs-on: ubuntu-latest
    steps:
      - name: print_fruits
        env:
          XYZ: ${{ github.event.commits }}
        run: echo $XYZ
