name: workflow_demo

on:
  push:
    branches: [main, feat/*]
  pull_request:
    branches: [feat/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: list npm config
        run: npm config list -l
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          key: node-modules-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
      - name: Install dependencies
        run: npm install
      - name: Build Product
        run: npm run build
# 使用 cache 缓存依赖2
