name: workflow_demo

on:
  pull_request_target:
    branches:
      - main

jobs:
  job:
    runs-on: aliyun
    env:
      GREETING: Hello
    steps:
      - name: Step Env
        env:
          OS: ${{runner.os}}
        run: echo $GREETING "${{ env.OS }}"
