name: workflow_demo2

on:
  push:
    branches: [main]

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
      - run: echo "Success!"
