name: workflow_demo

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: true
        default: ""

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: aliyun
    steps:
      - run: echo "Hello ${{ inputs.name }}!"
