name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  fruits:
    runs-on: ubuntu-latest
    env:
      A1: a
      B1: b-${{ env.A1 }}
    steps:
      - run: echo "${{ env.A1 }}"
      - run: echo $B1