name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  print_fruit_name:
    runs-on: ubuntu-latest
    env:
      KEY_1: hello
      KEY_2: ${{ env.KEY_1 }}
    steps:
      - run: echo $KEY_2
