name: workflow_demo

on:
  push:
    branches: [main]

env:
  ENV1: ENV1

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print_env
        env:
          STEP_ENV1: ${{ env.ENV1 }}
        run: echo "${{ env.STEP_ENV1 }}"
