name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VAR1: hello
    steps:
      - name: 正确使用 env
        # ✅ 在 env 字段中使用 ${{ env.VAR }}
        env:
          COMBINED: ${{ env.VAR1 }} world
        # ✅ 在 shell 脚本中使用 $变量名
        run: echo $COMBINED  # 输出: hello world