name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print_env
        env:
          ENV1: ENV1
          EVN2: ${{ env.ENV1 }}
        run: echo "${{ env.EVN2 }}"
