name: example_workflow_container
on:
  push:
    branches: [main]
jobs:
  print_os_name:
    runs-on: ubuntu-latest
    steps:
      - name: print_os_name
        env:
          OS: ${['linux', 'os', 'xx']}
        run: echo $OS
