name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  print_fruit_name:
    runs-on: ubuntu-latest
    env:
      fruits: ${{ fromJSON('{"key": "value"}') }}
    steps:
      - run: echo $fruits
