name: workflow_demo

on: pull_request

jobs:
  job:
    runs-on: aliyun
    steps:
      - name: "test"
        run: echo "test success!"
      - name: "deploy"
        if: ${{ success()}}
        run: echo "deploy!"
      - name: "notify"
        if: ${{ failure()}}
        run: echo "notify!"
      - name: "always"
        if: ${{ always()}}
        run: echo "always!"
