name: workflow_demo

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: my-caches
          path: ./src
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
