name: workflow_demo

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          key: node-modules-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
      - name: Install dependencies
        run: npm install
      - name: Build Product
        run: npm run build
      - name: list files
        run: ls -lha ~
# 使用 cache 缓存依赖1