name: workflow_demo

on:
  push:
    branches: [main]

jobs:
  print_fruit_name:
    runs-on: ubuntu-latest
    env:
      VAR1: hello
      VAR2: ${{ env.VAR1 }} world  # 正确：VAR1 已定义
    steps:
      - run: echo $VAR2
