name: workflow_demo

on:
  pull_request_target:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
      - run: echo "Success!"